Fixing env secrets for seed endpoint

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -72,16 +72,15 @@ jobs:
     needs: Deploy
     steps:
       - env:
-          SEED_SECRET: ${{ secrets.SEED_TOKEN }}
-        run: env | sort
-        # run: |
-        #   STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.authabl.com/seed" -H "Authorization: Bearer $SEED_TOKEN" -H "Content-Type: application/json")
+          SEED_TOKEN: ${{ secrets.SEED_TOKEN }}
+        run: |
+          STATUS_CODE=$(curl -s -o /dev/null -w "%{http_code}" -X POST "https://api.authabl.com/seed" -H "Authorization: Bearer $SEED_TOKEN" -H "Content-Type: application/json")
 
-        #   echo "HTTP Status: $STATUS_CODE"
+          echo "HTTP Status: $STATUS_CODE"
           
-        #   if [[ "$STATUS_CODE" -lt 200 || "$STATUS_CODE" -ge 300 ]]; then
-        #     echo "Request failed with status $STATUS_CODE"
-        #     exit 1
-        #   fi  
+          if [[ "$STATUS_CODE" -lt 200 || "$STATUS_CODE" -ge 300 ]]; then
+            echo "Request failed with status $STATUS_CODE"
+            exit 1
+          fi  
         
         
